### ISSUE TITLE
변수 선언 위치를 확인해주세요

### ISSUE THREAD

**Issue by callor** [sh1nheewon/Biz-2023-11-505-java#3]
![image](https://github.com/sh1nheewon/Biz-2023-11-505-java/assets/23270330/d731fb26-d984-496b-ba4f-c530704ccfa6)

이 변수들은 printScore() method 내에서 선언하는 것이 좋습니다

**Comment by sh1nheewon** [comment]
https://github.com/sh1nheewon/Biz-2023-11-505-java/tree/master/Java_900_OneDay_Score
